version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: ujjwal774/node_api
    ports:
      - "3000:3000"
    environment:
      - PG_DB=node_live_db
      - PG_USER=postgres
      - PG_PASSWORD=password
      - PG_HOST=node_db
    depends_on:
      - node_db
  
  node_db:
    container_name: node_db
    image: postgres:15-alpine3.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}



